# Generated by Django 6.0.3 on 2026-03-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_marketanalyticssnapshot_client_metrostation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='listings.realtor'),
        ),
    ]
