# Generated by Django 6.0.3 on 2026-04-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_image_file_and_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('generic', 'Общее'), ('deal_inquiry', 'Запрос на сделку от клиента')], default='generic', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_inquiry_notifications', to='listings.client'),
        ),
    ]
