# Generated by Django 6.0.3 on 2026-04-05 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'В процессе'), ('signed', 'Подписана'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('generic', 'Общее'), ('deal_inquiry', 'Запрос на сделку от клиента'), ('chat_message', 'Сообщение в чате по объекту')], default='generic', max_length=32),
        ),
        migrations.CreateModel(
            name='PropertyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='listings.property')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение чата по объекту',
                'verbose_name_plural': 'Сообщения чата по объектам',
                'ordering': ['created_at'],
            },
        ),
    ]
